#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Git pre-commit hook

# Obtain the list of files to analyze (exclude deleted files for example)
mapfile -t commited_files < <(git diff --cached --name-only --diff-filter=ACMR || true)

##############################
# Check formating with shfmt #
##############################

# Extract the shell files to be analyzed
mapfile -t shell_files < <(shfmt -f -- "${commited_files[@]}" || true)

# If we have at least one shell file, analyze them
if [[ ${#shell_files[@]} -gt 0 ]]; then
  shfmt -d -- "${shell_files[@]}"
  res=$?
  if [[ ${res} -ne 0 ]]; then
    echo "Commit aborted (${res}): shfmt error(s) found. See above this line for details."
    exit "${res}"
  fi
fi

######################################
# Check for warnings with shellcheck #
######################################

# If we have at least one shell file, analyze them
if [[ ${#shell_files[@]} -gt 0 ]]; then
  shellcheck --enable all -x -- "${shell_files[@]}"
  res=$?
  if [[ ${res} -ne 0 ]]; then
    echo "Commit aborted (${res}): shellcheck error(s) found. See above this line for details."
    exit "${res}"
  fi
fi

##################################
# Check for warnings with pylama #
##################################
pylama -o .pylama.ini -- "${commited_files[@]}"
res=$?
if [[ ${res} -ne 0 ]]; then
  echo "Commit aborted (${res}): pylama error(s) found. See above this line for details."
  exit "${res}"
fi
