#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This script is used to remotely configure the demers-qnap machine
# It takes over once the OS has already performed the following:
# 1. Installed the OS (XCP-ng) on baremetal
# 2. Reposiory homeinfra/demers-qnap has run locally to configure the machine
# 3. The management interface is up and reachable at IP ${XEN_MGT}
#
# It will then perform the following:
# 1. Configure QNAP's membership in the demers pool
# 2. Configure the network interfaces, according to demers topology
# 3. If needed, create, configure and start a VM for TrueNAS installation
#
# TODO:
# - Configure NTP servers in /etc/chrony.conf
# - TrueNAS VM
#
# Designed to run under the client Horizon docker container

setup() {
  if ! sdq_config; then
    logFatal "Failed to configure"
    return 1
  fi

  # Create the pool if it doesn't exist already
  if ! xe_pool_create "${POOL_NAME}"; then
    logFatal "Failed to create pool"
    return 1
  fi

  if ! configure_network; then
    return 1
  fi

  # Start TrueNAS installation
  if ! install_truenas; then
    return 1
  fi

  logInfo "Finished executing properly"
}

install_truenas() {
  # local truenas_res
  # xe_vm_prepare "${VM_NAME_NAS}" "${VM_RAM_NAS}" "${VM_VCPUS_NAS}" "${VM_DISK_NAS}"
  # truenas_res=$?
  # if [[ ${truenas_res} -eq 1 ]]; then
  #   logError "Failed to prepare VM"
  #   return 1
  # elif ! xe_vm_net_attach "${VM_NAME_NAS}" "${VM_NET_NAS}"; then
  #   logError "Failed to attach network to VM"
  #   return 1
  # elif ! xe_vm_pci_attach "${VM_NAME_NAS}" "${QN_STORAGE_PASS_THROUGH}"; then
  #   logError "Failed to attach PCI devices to VM"
  #   return 1
  # elif [[ ${truenas_res} -eq 0 ]]; then
  #   if ! mount_truenas_iso; then
  #     return 1
  #   else
  #     logInfo "TrueNAS Ready to install"
  #   fi
  # else
  #   logInfo "VM ready!"
  # fi

  # if ! xe_vm_start "${VM_NAME_NAS}"; then
  #   logError "Failed to start VM"
  #   return 1
  # fi

  mount_truenas_iso
}

mount_truenas_iso() {
  local my_iso_url iso_name

  if ! truenas_scale_latest_url my_iso_url; then
    return 1
  elif ! iso_populate_web iso_name "${my_iso_url}"; then
    return 1
  elif ! xe_vm_iso_attach "${VM_NAME_NAS}" "${iso_name}"; then
    return 1
  fi

  return 0
}

configure_network() {
  if ! xe_cleanup_network; then
    logFatal "Failed to cleanup networks"
    return 1
  fi

  # Figure out which NIC is which
  local mgt_mac_var net_mac_var mgt_mac net_mac
  mgt_mac_var="${MGT_NIC}_MAC"
  net_mac_var="${NET_NIC}_MAC"
  mgt_mac="${!mgt_mac_var}"
  net_mac="${!net_mac_var}"
  logInfo "Management NIC: ${MGT_NIC} (${mgt_mac})"
  logInfo "Network NIC: ${NET_NIC} (${net_mac})"

  if ! xe_vlan_config "${net_mac}" "${NETS}"; then
    logFatal "Failed to configure network interface"
    return 1
  fi

  # Wait for the device to appear on the network
  if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
    return 1
  fi
  if ! nu_wait_ping "${XEN_HOST}" "30"; then
    return 1
  fi

  # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
  if ! xe_create_connection "${XEN_HOST}"; then
    logFatal "Failed to connect to demers-qnap"
    return 1
  else
    logInfo "Connected successfully to demers-qnap"
  fi

  # Reconfigure the management interface
  # For some reasons, even tho the command works fine, it returns 1
  # Retrying solves the issue, because we re-validate everything and
  # determine it doesn't need to be called again.
  local nb_attempts res
  nb_attempts=2
  while true; do
    logDebug "Reconfiguring management IF (${nb_attempts} attempts left)"
    nb_attempts=$((nb_attempts - 1))
    xe_mgt_config "${mgt_mac}"
    res=$?
    if [[ ${res} -eq 0 ]]; then
      break
    elif [[ ${nb_attempts} -le 0 ]]; then
      logError "Failed to reconfigure management IF"
      return 1
    else
      logWarn "Failed to reconfigure management IF, retrying"
    fi
  done
}

sdq_config() {
  # Load configuration
  local configs config
  IFS=":" read -r -a configs <<<".config/default.env:${LOCAL_CONFIG}"
  for config in "${configs[@]}"; do
    if ! config_load "${SDQ_ROOT}/${config}"; then
      return 1
    fi
  done

  # Load dependencies
  # shellcheck disable=SC1091
  if ! source "${DIR_XAPI}/src/xe_vm.sh"; then
    logError "Failed to load xe_vm.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${DIR_SETUP}/src/net.sh"; then
    logError "Failed to load net.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${DIR_SETUP}/src/web.sh"; then
    logError "Failed to load web.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${SDQ_ROOT}/src/utils/iso.sh"; then
    logError "Failed to load iso.sh"
    return 1
  fi

  # Add the local xe executable to PATH
  PATH="${SDQ_ROOT}/libs/xe:${PATH}"
  export PATH

  # Test connection to the management interface of demers-qnap
  if ! xe_create_connection "${XEN_MGT}"; then
    logFatal "Failed to connect to demers-qnap's management interface"
    return 1
  else
    logInfo "Connected successfully to demers-qnap's management interface"
  fi

  # Load hardware configuration
  if ! config_load "${DIR_QNAP}/data/hardware.env"; then
    logFatal "Failed to load hardware configuration"
    return 1
  fi
}

# External variables
if [[ -z "${DIR_DOWNLOAD}" ]]; then DIR_DOWNLOAD=""; fi
if [[ -z "${DIR_QNAP}" ]]; then DIR_QNAP=""; fi
if [[ -z "${DIR_SETUP}" ]]; then DIR_SETUP=""; fi
if [[ -z "${DIR_XAPI}" ]]; then DIR_XAPI=""; fi
if [[ -z "${XEN_MGT}" ]]; then XEN_MGT=""; fi
if [[ -z "${XEN_HOST}" ]]; then XEN_HOST=""; fi
if [[ -z "${XEN_GW}" ]]; then XEN_GW=""; fi
if [[ -z "${MGT_NIC}" ]]; then MGT_NIC=""; fi
if [[ -z "${NET_NIC}" ]]; then NET_NIC=""; fi
if [[ -z "${NETS}" ]]; then NETS=""; fi
if [[ -z "${POOL_NAME}" ]]; then POOL_NAME=""; fi
if [[ -z "${VM_NAME_NAS}" ]]; then VM_NAME_NAS=""; fi
if [[ -z "${VM_DISK_NAS}" ]]; then VM_DISK_NAS=""; fi
if [[ -z "${VM_RAM_NAS}" ]]; then VM_RAM_NAS=""; fi
if [[ -z "${VM_VCPUS_NAS}" ]]; then VM_VCPUS_NAS=""; fi
if [[ -z "${VM_NET_NAS}" ]]; then VM_NET_NAS=""; fi
if [[ -z "${QN_STORAGE_PASS_THROUGH}" ]]; then QN_STORAGE_PASS_THROUGH=""; fi

# Constants
LOCAL_CONFIG=".config/demers.env:.config/demers-qnap.env:.config/local.env"

###########################
###### Startup logic ######
###########################

# Get directory of this script
# https://stackoverflow.com/a/246128
SDQ_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${SDQ_SOURCE}" ]]; do # resolve $SDQ_SOURCE until the file is no longer a symlink
  SDQ_ROOT=$(cd -P "$(dirname "${SDQ_SOURCE}")" >/dev/null 2>&1 && pwd)
  SDQ_SOURCE=$(readlink "${SDQ_SOURCE}")
  [[ ${SDQ_SOURCE} != /* ]] && SDQ_SOURCE=${SDQ_ROOT}/${SDQ_SOURCE} # if $SDQ_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SDQ_ROOT=$(cd -P "$(dirname "${SDQ_SOURCE}")" >/dev/null 2>&1 && pwd)
SDQ_ROOT=$(realpath "${SDQ_ROOT}/../../..")

# Determine BPKG's global prefix
if [[ -z "${PREFIX}" ]]; then
  if [[ $(id -u || true) -eq 0 ]]; then
    PREFIX="/usr/local"
  else
    PREFIX="${HOME}/.local"
  fi
fi

# Import dependencies
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/slf4.sh"; then
  echo "Failed to import slf4.sh"
  exit 1
fi
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/config.sh"; then
  logFatal "Failed to import config.sh"
fi

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  setup
  exit $?
fi
