---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use latest available version
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=512']
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-yaml
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0  # Use latest version from bmares
    hooks:
      - id: check-json5
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1  # Use the latest release of shfmt
    hooks:
      - id: shfmt
        args: [-i, '2', -d]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # Spellcheck uses version 0.9.0 installed locally
    hooks:
      - id: shellcheck
        args: [--enable, all, -x]
      - id: git-check
      - id: git-dirty
      - id: markdownlint
      - id: script-must-have-extension
        types: [shell, non-executable]
      - id: script-must-not-have-extension
        types: [shell, executable]
      - id: forbid-binary
  - repo: https://github.com/klen/pylama
    rev: 8.4.1  # Use the latest release of pylama
    hooks:
      - id: pylama
        args: [-o, .pylama.ini]
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.2  # Latest version from AleskaC
    hooks:
      - id: hadolint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0  # Latest version from adrien
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0  # Latest version from Google
    hooks:
      - id: yamlfmt
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0  # Latest version from macisamuele
    hooks:
      - id: pretty-format-ini
        args: [--autofix]
  - repo: local
    hooks:
      - id: my-dotenv-linter
        name: dotenv-linter
        pass_filenames: true
        language: system
        entry: dotenv-linter
        files: '^(.*\.env)$'
