#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This scripts is a shortcut to run everything.
# Thus, also document the different general steps.
# This is the main entry point

export LOCAL_CONFIG=".config/demers.env:.config/local.env"

# Configre local environment
./src/client/setup-local

# Deploy Horizon
./src/bootstrap/01-vm/horizon
