#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

setup() {
  if ! load_configuration; then
    return 1
  fi
}

load_configuration() {
  local configs config
  IFS=":" read -r -a configs <<<".config/default.env:${LOCAL_CONFIG}"
  for config in "${configs[@]}"; do
    if ! config_load "${SHA_ROOT}/${config}"; then
      return 1
    fi
  done
}

# Constants
LOCAL_CONFIG=".config/demers.env:.config/demers-qnap.env:.config/local.env"

###########################
###### Startup logic ######
###########################

# Get directory of this script
# https://stackoverflow.com/a/246128
SHA_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${SHA_SOURCE}" ]]; do # resolve $SHA_SOURCE until the file is no longer a symlink
  SHA_ROOT=$(cd -P "$(dirname "${SHA_SOURCE}")" >/dev/null 2>&1 && pwd)
  SHA_SOURCE=$(readlink "${SHA_SOURCE}")
  [[ ${SHA_SOURCE} != /* ]] && SHA_SOURCE=${SHA_ROOT}/${SHA_SOURCE} # if $SHA_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SHA_ROOT=$(cd -P "$(dirname "${SHA_SOURCE}")" >/dev/null 2>&1 && pwd)
SHA_ROOT=$(realpath "${SHA_ROOT}/../../../..")

# Determine BPKG's global prefix
if [[ -z "${PREFIX}" ]]; then
  if [[ $(id -u || true) -eq 0 ]]; then
    PREFIX="/usr/local"
  else
    PREFIX="${HOME}/.local"
  fi
fi

# Import dependencies
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/slf4.sh"; then
  echo "Failed to import slf4.sh"
  exit 1
fi
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/config.sh"; then
  logFatal "Failed to import config.sh"
fi

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  setup
  exit $?
fi
