#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This script is used to remotely configure the demers-sol machine
# It takes over once the OS has already performed the following:
# 1. Installed the OS (XCP-ng) on baremetal
# 2. Reposiory homeinfra/demers-sol has run locally to configure the machine
# 3. The management interface is up and reachable at IP ${XEN_MGT}
#
# It will then perform the following:
# 1. Configure the network interfaces, according to demers topology
# 2. Configure SOL's membership in the demers pool
# 3. If needed, create, configure and start a VM for HTPC usage
#
# TODO:
# - Configure NTP servers in /etc/chrony.conf
# - HTPC VM
#
# Designed to run under the client Horizon docker container

setup() {
  if ! sdq_config; then
    logError "Failed to configure"
    return 1
  elif ! configure_network; then
    logError "Failed to configure network"
    return 1
  elif ! configure_htpc; then
    logError "Failed to configure HTPC"
    return 1
  elif ! install_pugins; then
    logError "Failed to install plugins"
    return 1
  elif ! connect_qnap_to_sol; then
    logError "Failed to connect QNAP"
    return 1
  elif ! join_pool; then
    logError "Failed to join pool"
    return 1
  fi

  logInfo "Finished executing properly"
}

configure_network() {
  if ! xe_cleanup_network; then
    logFatal "Failed to cleanup networks"
    return 1
  fi

  # Figure out which NIC is which
  local mgt_mac_var net_mac_var mgt_mac net_mac
  mgt_mac_var="${MGT_NIC}_MAC"
  net_mac_var="${NET_NIC}_MAC"
  mgt_mac="${!mgt_mac_var}"
  net_mac="${!net_mac_var}"
  logInfo "Management NIC: ${MGT_NIC} (${mgt_mac})"
  logInfo "Network NIC: ${NET_NIC} (${net_mac})"

  if ! xe_vlan_config "${net_mac}" "${NETS}"; then
    logFatal "Failed to configure network interface"
    return 1
  fi

  # Wait for the device to appear on the network
  if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
    return 1
  fi
  if ! nu_wait_ping "${XEN_HOST}" "30"; then
    return 1
  fi

  # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
  if ! xe_create_connection "${XEN_HOST}"; then
    logFatal "Failed to connect to demers-qnap"
    return 1
  else
    logInfo "Connected successfully to demers-qnap"
  fi

  # Reconfigure the management interface
  # For some reasons, even tho the command works fine, it returns 1
  # Retrying solves the issue, because we re-validate everything and
  # determine it doesn't need to be called again.
  local nb_attempts res
  nb_attempts=2
  while true; do
    logDebug "Reconfiguring management IF (${nb_attempts} attempts left)"
    nb_attempts=$((nb_attempts - 1))
    xe_mgt_config "${mgt_mac}"
    res=$?
    if [[ ${res} -eq 0 ]]; then
      break
    elif [[ ${nb_attempts} -le 0 ]]; then
      logError "Failed to reconfigure management IF"
      return 1
    else
      logWarn "Failed to reconfigure management IF, retrying"
    fi
  done
}

configure_htpc() {
  if ! xe_vm_prepare "${HTPC_VM_NAME}" "${HTPC_VM_RAM}" "${HTPC_VM_VCPUS}" "${HTPC_VM_DISK}"; then
    logError "Failed to prepare ${HTPC_VM_NAME} VM"
    return 1
  elif ! xe_vm_net_attach "${HTPC_VM_NAME}" "${HTPC_VM_NET}"; then
    logError "Failed to attach network to VM"
    return 1
  elif ! xe_vm_pci_attach "${HTPC_VM_NAME}" "${PCI_GPU}"; then
    logError "Failed to attach PCI device to VM"
    return 1
  elif ! htpc_usb_mount; then
    logError "Failed to setup USB passthrough"
    return 1
  elif ! xe_vm_start "${HTPC_VM_NAME}"; then
    logError "Failed to start ${HTPC_VM_NAME}"
    return 1
  else
    logInfo "HTPC Ready to install"
  fi

  return 0
}

install_pugins() {
  # Find plugin files
  local files=()
  local file
  for file in "${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-sol/plugins/"*; do
    # Only keep files that start with start_, stop_ and power_
    if [[ $(basename "${file}") =~ ^(start_|stop_|power_).* ]]; then
      files+=("${file}")
    fi
  done

  # Determine plugin directory
  local plugin_dir git_root file_name tmp_file
  plugin_dir=${PLUGIN_DIR}
  cf_git_find_root git_root "${SDQ_SCRIPT}"

  # Get plugin_dir relative to git_root
  plugin_dir="${plugin_dir#"${git_root}"}"
  plugin_dir="${plugin_dir#/}"

  # Make it absolute to demers-sol
  plugin_dir="${SOL_HOME}/${plugin_dir}"
  logInfo "Plugin directory: ${plugin_dir}"

  # Configure the plugin
  local plug_file
  # shellcheck disable=SC2066
  for plug_file in "${files[@]}"; do
    file_name=$(basename "${plug_file}")
    logInfo "Installing plugin: ${file_name}"
    if ! tmp_file=$(mktemp); then
      logError "Failed to create temporary file"
      return 1
    elif ! cp "${plug_file}" "${tmp_file}"; then
      logError "Failed to copy start plugin file"
      return 1
    elif ! env_replace_in_place "${tmp_file}"; then
      logError "Failed to replace env variables in start plugin file"
      return 1
    fi

    # Install plugin
    local uri cmd res
    uri="scp://${XEN_HOST}:22${plugin_dir}/${file_name}"
    if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_USER}" "${XEN_PWD}" "force"; then
      logError "Failed to upload start plugin"
      return 1
    elif ! rm "${tmp_file}"; then
      logError "Failed to remove temporary file"
      return 1
    fi

    # Make the plugin executable
    cmd=(chmod +x "${plugin_dir}/${file_name}")
    if ! sol_exec res "${cmd[@]}"; then
      logError "Failed to make start plugin executable"
      return 1
    fi
  done
}

connect_qnap_to_sol() {
  # Need qnap config
  if ! config_load "${SDQ_ROOT}/.config/demers-qnap.env"; then
    return 1
  fi

  # Get qnap identity
  local qnap_id
  if ! ssh_identity_create qnap_id "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" 22; then
    logError "Failed to create demers identity"
    return 1
  fi

  # Restore sol config
  if ! config_load "${SDQ_ROOT}/.config/demers-sol.env"; then
    logError "Failed to load demers-sol configuration"
    return 1
  fi

  if ! ssh_identity_authorize "${qnap_id}" "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" 22; then
    logError "Could not authorize QNAP on SOL"
    return 1
  fi

  return 0
}

join_pool() {
  # TODO: Implement
  return 0
}

sol_exec() {
  local __ssh_res=${1}
  shift

  ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_HOST}" "22" "${@}"
  return $?
}

htpc_usb_mount() {
  local htpc_usb_devices
  IFS="," read -r -a htpc_usb_devices <<<"${USB_DEVICES}"

  local var_usb_vid var_usb_pid var_usb_sn
  for device in "${htpc_usb_devices[@]}"; do
    var_usb_vid="UDEV_VID_${device}"
    var_usb_pid="UDEV_PID_${device}"
    var_usb_sn="UDEV_SN_${device}"

    if xe_vm_usb_attach "${HTPC_VM_NAME}" "${!var_usb_vid}" "${!var_usb_pid}" "${!var_usb_sn}"; then
      logInfo "Attached USB device ${device} to ${HTPC_VM_NAME}"
    else
      logError "Failed to attach USB device ${device} to ${HTPC_VM_NAME}"
      return 1
    fi
  done
}

sdq_config() {
  # Determine BPKG's global prefix
  if [[ -z "${PREFIX}" ]]; then
    if [[ $(id -u || true) -eq 0 ]]; then
      PREFIX="/usr/local"
    else
      PREFIX="${HOME}/.local"
    fi
  fi

  # shellcheck disable=SC1091
  if ! source "${PREFIX}/lib/slf4.sh"; then
    echo "Failed to import slf4.sh"
    exit 1
  elif ! source "${PREFIX}/lib/config.sh"; then
    logError "Failed to import config.sh"
    return 1
  fi

  # Load configuration
  local configs config
  IFS=":" read -r -a configs <<<".config/default.env:${LOCAL_CONFIG}"
  for config in "${configs[@]}"; do
    if ! config_load "${SDQ_ROOT}/${config}"; then
      return 1
    fi
  done

  # shellcheck disable=SC1091
  if [[ -z "${DIR_BIN}" ]]; then
    logError "DIR_BIN is not set"
    return 1
  elif [[ -z "${DIR_SOL}" ]]; then
    logError "DIR_SOL is not set"
    return 1
  elif [[ -z "${SOL_HOME}" ]]; then
    logError "SOL_HOME is not set"
    return 1
  elif ! source "${DIR_XAPI}/src/xe_vm.sh"; then
    logError "Failed to load xe_vm.sh"
    return 1
  elif ! source "${DIR_SETUP}/src/net.sh"; then
    logError "Failed to load net.sh"
    return 1
  elif ! source "${DIR_SETUP}/src/web.sh"; then
    logError "Failed to load web.sh"
    return 1
  elif ! source "${DIR_SETUP}/src/env.sh"; then
    logError "Failed to load env.sh"
    return 1
  elif ! source "${SDQ_ROOT}/src/utils/iso.sh"; then
    logError "Failed to load iso.sh"
    return 1
  fi

  # Download XE CLI utility
  if ! nu_file_download "${DIR_BIN}/xe" "scp://${XEN_HOST}:22/opt/xensource/bin/xe" \
    "${XEN_USER}" "${XEN_PWD}"; then
    logFatal "Failed to download xe"
    return 1
  fi

  # Configure it into PATH
  PATH="${DIR_BIN}:${PATH}"
  export PATH

  # Test connection to the management interface of demers-qnap
  if ! xe_create_connection "${XEN_MGT}"; then
    logError "Failed to connect to demers-qnap's management interface"
    return 1
  else
    logInfo "Connected successfully to demers-qnap's management interface"
  fi

  # Load sol configuration
  if ! config_load "${DIR_SOL}/data/local.env"; then
    logError "Failed to load local configuration"
    return 1
  elif ! config_load "${DIR_SOL}/data/hardware.env"; then
    logError "Failed to load hardware configuration"
    return 1
  elif [[ -z "${XEN_HOST}" ]]; then
    logError "XEN_HOST is not set"
    return 1
  elif [[ -z "${XEN_USER}" ]]; then
    logError "XEN_USER is not set"
    return 1
  elif [[ -z "${XEN_PWD}" ]]; then
    logError "XEN_PWD is not set"
    return 1
  elif [[ -z "${XEN_ISO_USER}" ]]; then
    logError "XEN_ISO_USER is not set"
    return 1
  elif [[ -z "${XEN_ISO_PWD}" ]]; then
    logError "XEN_ISO_PWD is not set"
    return 1
  elif [[ -z "${XEN_MGT}" ]]; then
    logError "XEN_MGT is not set"
    return 1
  elif [[ -z "${XEN_GW}" ]]; then
    logError "XEN_GW is not set"
    return 1
  elif [[ -z "${MGT_NIC}" ]]; then
    logError "MGT_NIC is not set"
    return 1
  elif [[ -z "${NET_NIC}" ]]; then
    logError "NET_NIC is not set"
    return 1
  elif [[ -z "${NETS}" ]]; then
    logError "NETS is not set"
    return 1
  elif [[ -z "${POOL_NAME}" ]]; then
    logError "POOL_NAME is not set"
    return 1
  elif [[ -z "${HTPC_VM_NAME}" ]]; then
    logError "HTPC_VM_NAME is not set"
    return 1
  elif [[ -z "${HTPC_VM_RAM}" ]]; then
    logError "HTPC_VM_RAM is not set"
    return 1
  elif [[ -z "${HTPC_VM_VCPUS}" ]]; then
    logError "HTPC_VM_VCPUS is not set"
    return 1
  elif [[ -z "${HTPC_VM_DISK}" ]]; then
    logError "HTPC_VM_DISK is not set"
    return 1
  elif [[ -z "${HTPC_VM_NET}" ]]; then
    logError "HTPC_VM_NET is not set"
    return 1
  elif [[ -z "${PCI_GPU}" ]]; then
    logError "PCI_GPU is not set"
    return 1
  elif [[ -z "${USB_DEVICES}" ]]; then
    logError "USB_DEVICES is not set"
    return 1
  elif [[ -z "${PLUGIN_DIR}" ]]; then
    logError "PLUGIN_DIR is not set"
    return 1
  fi
}

# Constants
LOCAL_CONFIG=".config/demers.env:.config/demers-sol.env:.config/local.env"

###########################
###### Startup logic ######
###########################
SDQ_SCRIPT="${0}"

# Get directory of this script
# https://stackoverflow.com/a/246128
SDQ_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${SDQ_SOURCE}" ]]; do # resolve $SDQ_SOURCE until the file is no longer a symlink
  SDQ_ROOT=$(cd -P "$(dirname "${SDQ_SOURCE}")" >/dev/null 2>&1 && pwd)
  SDQ_SOURCE=$(readlink "${SDQ_SOURCE}")
  [[ ${SDQ_SOURCE} != /* ]] && SDQ_SOURCE=${SDQ_ROOT}/${SDQ_SOURCE} # if $SDQ_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SDQ_ROOT=$(cd -P "$(dirname "${SDQ_SOURCE}")" >/dev/null 2>&1 && pwd)
SDQ_ROOT=$(realpath "${SDQ_ROOT}/../../../..")

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  setup
  exit $?
fi
