#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This script is used to manage the development container.
#
# NOTE: Designed for execution under Ubuntu WSL (Windows Subsystem for Linux)
set -o pipefail

main() {
  # Check dependencies
  if ! dependencies; then
    logFatal "Failed to load dependencies"
  fi

  local cfg env
  if ! parse cfg env; then
    logFatal "Failed to parse arguments"
  fi

  logInfo "Calling ${cfg} container for environment: ${env}"

  if ! eval "co_${cfg}" "${env}"; then
    logFatal "Failed to call ${cfg} container for environment: ${env}"
  fi
}

dependencies() {
  # Check if docker is installed
  if ! command -v docker >/dev/null; then
    logFatal "Docker is not installed. Please install it first."
  elif ! command -v docker-compose >/dev/null; then
    logFatal "Docker-compose is not installed. Please install it first."
  elif ! command -v semver >/dev/null; then
    logFatal "Semver is not installed. Please install it first."
  fi

  local configs config
  IFS=":" read -r -a configs <<<".config/default.env:${LOCAL_CONFIG}"
  for config in "${configs[@]}"; do
    if ! config_load "${CO_ROOT}/${config}"; then
      return 1
    fi
  done

  # shellcheck source=external/demers-qnap/external/setup/src/git.sh
  if ! source "${DIR_SETUP}/src/git.sh"; then
    return 1
  fi

  return 0
}

# Buid the container
#
# Parameters:
#   $1[in]: Name of the service to build
co_build() {
  local _env="$1"

  local res
  local args=()
  local cmd=()

  pushd "${CO_ROOT}/src" >/dev/null || logFatal "Failed change directory to ${CO_ROOT}/src"

  # Variables
  ver=$(semver)
  args+=("CLIENT_USER=${CLIENT_USER}")
  args+=("CLIENT_GROUP=${CLIENT_GROUP}")
  args+=("IG_PORT=${IG_PORT}")
  args+=("SERVER_PORT=${SERVER_PORT}")

  if [[ "${_env}" == "dev" ]]; then
    args+=("DEV_USER=${DEV_USER}")
    args+=("DEV_GROUP=${DEV_GROUP}")
    args+=("DEV_UID=$(id -u)")
    args+=("DEV_GID=$(id -g)")
  fi

  cmd=("${args[@]}" "docker-compose" "build" "--build-arg" "VER_VERSION=${ver}")
  logInfo "Building image:\n${cmd[*]}"

  if ! eval "${cmd[*]}" "prod_base"; then
    logFatal "Failed to build base image"
  elif ! eval "${cmd[*]}" "prod"; then
    logFatal "Failed to build prod image"
  fi
  if [[ "${_env}" == "dev" ]]; then
    if ! eval "${cmd[*]}" "${_env}"; then
      logFatal "Failed to build dev image"
    fi
  fi

  # if ! eval "${cmd[*]}" "${_env}"; then
  #     logFatal "Failed to build image"
  # fi

  logInfo "Image built"

  popd >/dev/null || logFatal "Failed to change directory back"
}

# Start the container
#
# Parameters:
#   $1[in]: Container to start
# shellcheck disable=SC2317
co_start() {
  local _env="$1"
  local container_name="${CO_NAME_PREFIX}${_env}"
  local image_name="${container_name}${CO_IMAGE_SUFFIX}"

  # Check if container is found
  if docker ps -a --format '{{.Names}}' | grep -q "^""${container_name}""$"; then
    logInfo "Container ${container_name} found"

    # Check container status
    local status
    status=$(docker inspect -f '{{.State.Running}}' "${container_name}")

    if [[ "${status}" == "true" ]]; then
      logInfo "Container is already running. Nothing to do."
    else
      logInfo "Restarting container..."
      docker container restart "${container_name}" >/dev/null
      logInfo "Container restarted"
    fi
  # Container not found
  else
    logInfo "Container ${container_name} NOT found"

    local cmd res
    if ! co_prepare_cmd cmd "${_env}" "${container_name}"; then
      logFatal "Failed to prepare command"
    fi

    logInfo "Starting container using command:\n${cmd[*]}"
    if ! "${cmd[@]}" >/dev/null; then
      logFatal "Failed to start container"
    fi
    logInfo "Container started"
  fi
}

# Stop the container
#
# Parameters:
#   $1[in]: Container to stop
# shellcheck disable=SC2317
co_stop() {
  local _env="$1"
  local container_name="${CO_NAME_PREFIX}${_env}"

  # First check if container exists
  if docker ps -q --filter "name=${container_name}" | grep -q .; then
    logInfo "Stopping container..."
    if ! docker stop "${container_name}" >/dev/null; then
      logFatal "Failed to stop container"
    fi
    logInfo "Container stopped"
  else
    logWarn "No container named \"${container_name}\" was found to be running!"
  fi
}

# Delete the container
#
# Parameters:
#   $1[in]: Container to stop
# shellcheck disable=SC2317
co_delete() {
  local _env="$1"
  local container_name="${CO_NAME_PREFIX}${_env}"

  if docker ps -a --format '{{.Names}}' | grep -q "^""${container_name}""$"; then

    # Check container status
    local status
    status=$(docker inspect -f '{{.State.Running}}' "${container_name}")

    if [[ "${status}" == "true" ]]; then
      logWarn "Container is currently running. Stop it first."
      co_stop "${_env}"
    fi

    logInfo "Deleting container..."
    if ! docker rm "${container_name}" >/dev/null; then
      logFatal "Failed to delete container"
    fi
    logInfo "Container deleted"
  else
    logWarn "No contained named \"${container_name}\" was found!"
  fi
}

# Execute a command in the container and return after completion
#
# Parameters:
#  $1[in]: Container to execute command in
# shellcheck disable=SC2317
co_exec() {
  local _env="$1"
  local container_name="${CO_NAME_PREFIX}${_env}"
  local image_name="${container_name}${CO_IMAGE_SUFFIX}"

  local cmd res
  if ! co_prepare_cmd cmd "${_env}" ""; then
    logFatal "Failed to prepare command"
  fi
  cmd+=("${EXEC_ARGS[@]}")

  logInfo "Executing command in container using command:\n${cmd[*]}"
  "${cmd[@]}"
  res=$?
  if [[ ${res} -ne 0 ]]; then
    logError "Failed to execute command in container"
  fi

  # shellcheck disable=SC2248
  exit ${res}
}

# Prepare the command to be executed
#
# Parameters:
#   $1[out]: Command to prepare
#   $2[in]: Environment to prepare command for
#   $3[in]: Container name
co_prepare_cmd() {
  declare -n _cmd="$1"
  local _env="$2"
  local _name="$3"

  if ! docker images -q "${image_name}" | grep -q .; then
    logInfo "Image \"${image_name}\" does not seem to exist. Try building-it first."
    build "${_env}"
  fi

  local desired_root top_root relative_root new_home
  desired_root=${CO_CWD}

  if ! git_find_root top_root "${desired_root}"; then
    logFatal "Failed to find git root"
  fi

  # Find relative path to root of repo
  relative_root="${desired_root#"${top_root}"}"

  # Pick the correct user based on env
  local user=${CLIENT_USER}
  if [[ "${_env}" == "dev" ]]; then
    user=${DEV_USER}
  fi
  new_home="/home/${user}"

  # TODO: Maybe add the "--init" option later
  #       Maybe we'll have to define ports later. Ex: -p 10080:8080 -p 10022:22 -p 7556-7559:7556-7559
  _cmd=("docker" "run" "--user" "${user}")
  if [[ -z "${_name}" ]]; then
    _cmd+=("--rm" "-it")
  else
    _cmd+=("-dit")
  fi
  _cmd+=("-v" "${HOME}/.ssh:${new_home}/.ssh")
  _cmd+=("-v" "${HOME}/.sops:${new_home}/.sops")
  _cmd+=("-v" "${top_root}:${new_home}/src")

  # If age key starts with ${HOME}, do substitution
  if [[ "${SOPS_AGE_KEY_FILE}" == "${HOME}"* ]]; then
    # Replace ${HOME} in the path
    SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE#"${HOME}"}"
    SOPS_AGE_KEY_FILE="${new_home}${SOPS_AGE_KEY_FILE}"
  fi
  _cmd+=("-e" "SOPS_AGE_KEY_FILE=${SOPS_AGE_KEY_FILE}")
  _cmd+=("-e" "VER_HOST=$(hostname)")
  _cmd+=("-w" "${new_home}/src${relative_root}")
  if [[ -n "${_name}" ]]; then
    cmd+=("--name" "${_name}")
  fi
  cmd+=("${image_name}")
}

# Parse arguments received via command line
#
# Parameters:
#   $_fct[out]: configuration to make
#   $_env[out]: environnement to configure
parse() {
  declare -n _cfg="$1"
  declare -n _env="$2"

  # Default values
  _cfg="start"
  _env="dev"

  local short long opts arg
  short="hv"
  long="help,version"

  # First pass to scan for "--"
  declare -g -a EXEC_ARGS=()
  local real_args=()
  local is_command=false
  for arg in "${CO_ARGS[@]}"; do
    logTrace "Analyzing argument: ${arg}"
    if [[ "${is_command}" == "true" ]]; then
      logTrace "Intercepting ${arg}"
      EXEC_ARGS+=("${arg}")
    elif [[ "${arg}" == "--" ]]; then
      logTrace "From now on we are intercepting"
      is_command=true
    else
      logTrace "Keeping ${arg}"
      real_args+=("${arg}")
    fi
  done

  if ! opts=$(getopt --options "${short}" --long "${long}" --name "${CO_ME}" -- "${real_args[@]}"); then
    logFatal "Failed to parse arguments"
  fi

  eval set -- "${opts}"
  while true; do
    logTrace "Parsing option: ${1}"
    case "$1" in
    -h | --help)
      print_help
      exit 0
      ;;
    -v | --version)
      cd "${CO_ROOT}" && semver
      exit 0
      ;;
    --)
      shift # Remaining arguments are positional
      break
      ;;
    *)
      logFatal "Unknown option: $1"
      ;;
    esac
  done

  # Handle positional arguments
  local arg_counter=0
  while [[ $# -gt 0 ]]; do
    arg_counter=$((arg_counter + 1))
    arg=${1}
    shift
    logTrace "Parsing argument ${arg_counter}: ${arg}"
    case ${arg_counter} in
    1)
      case ${arg} in
      start | stop | build | delete | exec)
        _cfg="${arg}"
        ;;
      *)
        logFatal "Unknown or too many argument: ${arg}"
        ;;
      esac
      ;;
    2)
      case ${arg} in
      dev | prod)
        _env="${arg}"
        ;;
      *)
        logFatal "Unknown or too many argument: ${arg}"
        ;;
      esac
      ;;
    *)
      logFatal "Unknown or too many argument: ${arg}"
      break
      ;;
    esac
  done
}

print_help() {
  cat <<EOF
Script managing the docker environment. This is the entry point to switch into the environment

Usage: ${CO_ME} [options]
       ${CO_ME} <command> [<env>]
       ${CO_ME} exec [<env>] -- <cmd>

Command <command>:
  build         Build the container
  start         Start the container (will build if necessary)
  stop          Stop the container
  del           Delete the container
  exec          Execute a command in the container

Environment <env>:
  prod         Production environment
  dev          Development environment [Default]

Options:
  -h,--help     Print this usage message
  -v,--version  Print the version of this tool
  --            End of cmdline processing, what follows will be passed to the container
EOF
}

# Variables loaded externally
if [[ -z "${DIR_SETUP}" ]]; then DIR_SETUP=""; fi

# Constants
readonly CO_NAME_PREFIX="horizon-"
readonly CO_IMAGE_SUFFIX="-image"
LOCAL_CONFIG=".config/local.env"

###########################
###### Startup logic ######
###########################
CO_ARGS=("$@")
CO_ME="$(basename "${BASH_SOURCE[0]}")"
CO_CWD=$(pwd)

# Get directory of this script
# https://stackoverflow.com/a/246128
CO_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${CO_SOURCE}" ]]; do # resolve $CO_SOURCE until the file is no longer a symlink
  CO_ROOT=$(cd -P "$(dirname "${CO_SOURCE}")" >/dev/null 2>&1 && pwd)
  CO_SOURCE=$(readlink "${CO_SOURCE}")
  [[ ${CO_SOURCE} != /* ]] && CO_SOURCE=${CO_ROOT}/${CO_SOURCE} # if $CO_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
CO_ROOT=$(cd -P "$(dirname "${CO_SOURCE}")" >/dev/null 2>&1 && pwd)
CO_ROOT=$(realpath "${CO_ROOT}/../..")

# Determine BPKG's global prefix
if [[ -z "${PREFIX}" ]]; then
  if [[ $(id -u || true) -eq 0 ]]; then
    PREFIX="/usr/local"
  else
    PREFIX="${HOME}/.local"
  fi
fi

# Import dependencies
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/slf4.sh"; then
  echo "Failed to import slf4.sh"
  exit 1
fi
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/config.sh"; then
  logFatal "Failed to import config.sh"
fi

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  main
  exit $?
fi
