#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This script is used to remotely configure the demers-qnap machine
# It takes over once the OS has already performed the following:
# 1. Installed the OS (XCP-ng) on baremetal
# 2. Reposiory homeinfra/demers-qnap has run locally to configure the machine
# 3. The management interface is up and reachable at IP ${XEN_MGT}
#
# It will then perform the following:
# 1. Configure QNAP's membership in the demers pool
# 2. Configure the network interfaces, according to demers topology
# 3. If needed, create, configure and start a VM for TrueNAS installation
#
# TODO:
# - Configure NTP servers in /etc/chrony.conf
# - TrueNAS VM
#
# Designed to run under the client Horizon docker container

setup() {
  if ! sdq_config; then
    logFatal "Failed to configure"
    return 1
  fi

  # Create the pool if it doesn't exist already
  if ! xe_pool_create "${POOL_NAME}"; then
    logFatal "Failed to create pool"
    return 1
  fi

  if ! configure_network; then
    return 1
  fi

  # Start TrueNAS installation
  if ! install_truenas; then
    return 1
  fi

  logInfo "Finished executing properly"
}

install_truenas() {
  local truenas_res

  if ! config_load "${SDQ_ROOT}/external/demers-qnap/data/local.env"; then
    logFatal "Failed to load local configuration"
    return 1
  fi

  if [[ -z "${XCP_CRITICAL_TAG}" ]]; then
    logFatal "XCP_CRITICAL_TAG is not set. Did you load local.env?"
    return 1
  fi

  xe_vm_prepare "${VM_NAME_NAS}" "${VM_RAM_NAS}" "${VM_VCPUS_NAS}" "${VM_DISK_NAS}"
  truenas_res=$?
  if [[ ${truenas_res} -eq 1 ]]; then
    logError "Failed to prepare VM"
    return 1
  elif ! xe_vm_tag_add "${VM_NAME_NAS}" "${XCP_CRITICAL_TAG}"; then
    logError "Failed to tag VM as critical"
    return 1
  elif ! xe_vm_net_attach "${VM_NAME_NAS}" "${VM_NET_NAS}"; then
    logError "Failed to attach network to VM"
    return 1
  elif [[ ${truenas_res} -eq 2 ]]; then
    if ! mount_truenas_iso; then
      return 1
    else
      logInfo "TrueNAS Ready to install"
    fi
  fi

  # This will start the plugin (and thus, the VM)
  if ! update_plugin; then
    return 1
  fi
}

update_plugin() {
  local start_file stop_file
  start_file="${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-qnap/start_halley"
  stop_file="${SDQ_ROOT}/src/bootstrap/00-baremetal/demers-qnap//stop_halley"

  if [[ -z "${PLUGIN_DIR}" ]]; then
    logFatal "No plugin directory set"
    return 1
  elif [[ -z "${QNAP_HOME}" ]]; then
    logFatal "QNAP_HOME is not set"
    return 1
  elif [[ ! -f "${start_file}" ]]; then
    logFatal "Start plugin file not found"
    return 1
  elif [[ ! -f "${stop_file}" ]]; then
    logFatal "Stop plugin file not found"
    return 1
  fi

  # Determine plugin directory
  local plugin_dir git_root file_name tmp_file
  plugin_dir=${PLUGIN_DIR}
  cf_git_find_root git_root "${SDQ_SCRIPT}"

  # Get plugin_dir relative to git_root
  plugin_dir="${plugin_dir#"${git_root}"}"
  plugin_dir="${plugin_dir#/}"

  # Make it absolute to demers-qnap
  plugin_dir="${QNAP_HOME}/${plugin_dir}"
  logInfo "Plugin directory: ${plugin_dir}"

  # Configure the plugin
  local plug_file
  for plug_file in "${start_file}" "${stop_file}"; do
    file_name=$(basename "${plug_file}")
    if ! tmp_file=$(mktemp); then
      logError "Failed to create temporary file"
      return 1
    elif ! cp "${plug_file}" "${tmp_file}"; then
      logError "Failed to copy start plugin file"
      return 1
    elif ! env_replace_in_place "${tmp_file}"; then
      logError "Failed to replace env variables in start plugin file"
      return 1
    fi

    # Install plugin
    local uri cmd res
    uri="scp://${XEN_MGT}:22${plugin_dir}/${file_name}"
    if ! nu_file_upload "${tmp_file}" "${uri}" "${XEN_ISO_USER}" "${XEN_ISO_PWD}" "force"; then
      logError "Failed to upload start plugin"
      return 1
    elif ! rm "${tmp_file}"; then
      logError "Failed to remove temporary file"
      return 1
    fi

    # Make the plugin executable
    cmd=(chmod +x "${plugin_dir}/${file_name}")
    if ! qnap_exec res "${cmd[@]}"; then
      logError "Failed to make start plugin executable"
      return 1
    fi
  done

  # Exexute the plugin to start the VM
  cmd=("${plugin_dir}/$(basename "${start_file}")")
  if ! qnap_exec res "${cmd[@]}"; then
    logError "Failed to execute start plugin"
    return 1
  fi

  return 0
}

# Execute a command on qnap
#
# Parameters:
#   $1[out]: command output
#   $@[in]: command
qnap_exec() {
  local __ssh_res=${1}
  shift

  nu_ssh_exec "${__ssh_res}" "${XEN_USER}" "${XEN_PWD}" "${XEN_MGT}" "22" "${@}"
  return $?
}

mount_truenas_iso() {
  local my_iso_url truenas_iso_name

  if ! truenas_scale_latest_url my_iso_url; then
    return 1
  elif ! iso_populate_web truenas_iso_name "${my_iso_url}"; then
    return 1
  elif ! xe_vm_iso_attach "${VM_NAME_NAS}" "${truenas_iso_name}"; then
    return 1
  fi

  return 0
}

configure_network() {
  if ! xe_cleanup_network; then
    logFatal "Failed to cleanup networks"
    return 1
  fi

  # Figure out which NIC is which
  local mgt_mac_var net_mac_var mgt_mac net_mac
  mgt_mac_var="${MGT_NIC}_MAC"
  net_mac_var="${NET_NIC}_MAC"
  mgt_mac="${!mgt_mac_var}"
  net_mac="${!net_mac_var}"
  logInfo "Management NIC: ${MGT_NIC} (${mgt_mac})"
  logInfo "Network NIC: ${NET_NIC} (${net_mac})"

  if ! xe_vlan_config "${net_mac}" "${NETS}"; then
    logFatal "Failed to configure network interface"
    return 1
  fi

  # # Wait for the device to appear on the network
  # if ! nu_wait_dns "${XEN_HOST}" "${XEN_GW}" "30"; then
  #   return 1
  # fi
  # if ! nu_wait_ping "${XEN_HOST}" "30"; then
  #   return 1
  # fi

  # # Reconfigure to use the dynamic interface, so we can reconfigure the mgt one
  # if ! xe_create_connection "${XEN_HOST}"; then
  #   logFatal "Failed to connect to demers-qnap"
  #   return 1
  # else
  #   logInfo "Connected successfully to demers-qnap"
  # fi

  # Reconfigure the management interface
  # For some reasons, even tho the command works fine, it returns 1
  # Retrying solves the issue, because we re-validate everything and
  # determine it doesn't need to be called again.
  local nb_attempts res
  nb_attempts=2
  while true; do
    logDebug "Reconfiguring management IF (${nb_attempts} attempts left)"
    nb_attempts=$((nb_attempts - 1))
    xe_mgt_config "${mgt_mac}"
    res=$?
    if [[ ${res} -eq 0 ]]; then
      break
    elif [[ ${nb_attempts} -le 0 ]]; then
      logError "Failed to reconfigure management IF"
      return 1
    else
      logWarn "Failed to reconfigure management IF, retrying"
    fi
  done
}

sdq_config() {
  # Load configuration
  local configs config
  IFS=":" read -r -a configs <<<".config/default.env:${LOCAL_CONFIG}"
  for config in "${configs[@]}"; do
    if ! config_load "${SDQ_ROOT}/${config}"; then
      return 1
    fi
  done

  if [[ -z "${DIR_QNAP}" ]]; then
    logFatal "DIR_QNAP is not set"
    return 1
  fi

  # Load dependencies
  # shellcheck disable=SC1091
  if ! source "${DIR_XAPI}/src/xe_vm.sh"; then
    logError "Failed to load xe_vm.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${DIR_SETUP}/src/net.sh"; then
    logError "Failed to load net.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${DIR_SETUP}/src/web.sh"; then
    logError "Failed to load web.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${DIR_SETUP}/src/env.sh"; then
    logError "Failed to load env.sh"
    return 1
  fi
  # shellcheck disable=SC1091
  if ! source "${SDQ_ROOT}/src/utils/iso.sh"; then
    logError "Failed to load iso.sh"
    return 1
  fi

  # Add the local xe executable to PATH
  PATH="${SDQ_ROOT}/libs/xe:${PATH}"
  export PATH

  # Test connection to the management interface of demers-qnap
  if ! xe_create_connection "${XEN_MGT}"; then
    logFatal "Failed to connect to demers-qnap's management interface"
    return 1
  else
    logInfo "Connected successfully to demers-qnap's management interface"
  fi

  # Load hardware configuration
  if ! config_load "${DIR_QNAP}/data/hardware.env"; then
    logFatal "Failed to load hardware configuration"
    return 1
  fi

  if [[ -z "${XEN_HOST}" ]]; then
    logFatal "XEN_HOST is not set"
    return 1
  elif [[ -z "${XEN_USER}" ]]; then
    logFatal "XEN_USER is not set"
    return 1
  elif [[ -z "${XEN_PWD}" ]]; then
    logFatal "XEN_PWD is not set"
    return 1
  elif [[ -z "${XEN_ISO_USER}" ]]; then
    logFatal "XEN_ISO_USER is not set"
    return 1
  elif [[ -z "${XEN_ISO_PWD}" ]]; then
    logFatal "XEN_ISO_PWD is not set"
    return 1
  elif [[ -z "${XEN_MGT}" ]]; then
    logFatal "XEN_MGT is not set"
    return 1
  elif [[ -z "${XEN_GW}" ]]; then
    logFatal "XEN_GW is not set"
    return 1
  elif [[ -z "${MGT_NIC}" ]]; then
    logFatal "MGT_NIC is not set"
    return 1
  elif [[ -z "${NET_NIC}" ]]; then
    logFatal "NET_NIC is not set"
    return 1
  elif [[ -z "${NETS}" ]]; then
    logFatal "NETS is not set"
    return 1
  elif [[ -z "${VM_NAME_NAS}" ]]; then
    logFatal "VM_NAME_NAS is not set"
    return 1
  elif [[ -z "${VM_RAM_NAS}" ]]; then
    logFatal "VM_RAM_NAS is not set"
    return 1
  elif [[ -z "${VM_VCPUS_NAS}" ]]; then
    logFatal "VM_VCPUS_NAS is not set"
    return 1
  elif [[ -z "${VM_DISK_NAS}" ]]; then
    logFatal "VM_DISK_NAS is not set"
    return 1
  elif [[ -z "${VM_NET_NAS}" ]]; then
    logFatal "VM_NET_NAS is not set"
    return 1
  elif [[ -z "${POOL_NAME}" ]]; then
    logFatal "POOL_NAME is not set"
    return 1
  fi
}

# Constants
LOCAL_CONFIG=".config/demers.env:.config/demers-qnap.env:.config/local.env"

###########################
###### Startup logic ######
###########################
SDQ_SCRIPT="${0}"

# Get directory of this script
# https://stackoverflow.com/a/246128
SDQ_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${SDQ_SOURCE}" ]]; do # resolve $SDQ_SOURCE until the file is no longer a symlink
  SDQ_ROOT=$(cd -P "$(dirname "${SDQ_SOURCE}")" >/dev/null 2>&1 && pwd)
  SDQ_SOURCE=$(readlink "${SDQ_SOURCE}")
  [[ ${SDQ_SOURCE} != /* ]] && SDQ_SOURCE=${SDQ_ROOT}/${SDQ_SOURCE} # if $SDQ_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SDQ_ROOT=$(cd -P "$(dirname "${SDQ_SOURCE}")" >/dev/null 2>&1 && pwd)
SDQ_ROOT=$(realpath "${SDQ_ROOT}/../../../..")

# Determine BPKG's global prefix
if [[ -z "${PREFIX}" ]]; then
  if [[ $(id -u || true) -eq 0 ]]; then
    PREFIX="/usr/local"
  else
    PREFIX="${HOME}/.local"
  fi
fi

# Import dependencies
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/slf4.sh"; then
  echo "Failed to import slf4.sh"
  exit 1
fi
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/config.sh"; then
  logFatal "Failed to import config.sh"
fi

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  setup
  exit $?
fi
