#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# XCP-ng plugin file to configure Halley on shutdown

plugin_halley_stop() {
  logInfo "Stopping Halley"
  return 0
}

###########################
###### Startup logic ######
###########################

# Get directory of this script
# https://stackoverflow.com/a/246128
SHH_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${SHH_SOURCE}" ]]; do # resolve $SHH_SOURCE until the file is no longer a symlink
  SHH_ROOT=$(cd -P "$(dirname "${SHH_SOURCE}")" >/dev/null 2>&1 && pwd)
  SHH_SOURCE=$(readlink "${SHH_SOURCE}")
  [[ ${SHH_SOURCE} != /* ]] && SHH_SOURCE=${SHH_ROOT}/${SHH_SOURCE} # if $SHH_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SHH_ROOT=$(cd -P "$(dirname "${SHH_SOURCE}")" >/dev/null 2>&1 && pwd)
SHH_ROOT=$(realpath "${SHH_ROOT}/../..")

# Determine BPKG's global prefix
if [[ -z "${PREFIX}" ]]; then
  if [[ $(id -u || true) -eq 0 ]]; then
    PREFIX="/usr/local"
  else
    PREFIX="${HOME}/.local"
  fi
fi

# Import dependencies
# shellcheck disable=SC1091
if ! source "${PREFIX}/lib/slf4.sh"; then
  echo "Failed to import slf4.sh"
  exit 1
fi

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  plugin_halley_stop
  exit $?
fi
