#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

setup() {
  if ! load_configuration; then
    return 1
  elif ! configure_htpc; then
    return 1
  fi
}

configure_htpc() {
  if ! xe_vm_prepare "${HTPC_VM_NAME}" "${HTPC_VM_RAM}" "${HTPC_VM_VCPUS}" "${HTPC_VM_DISK}"; then
    logError "Failed to prepare ${HTPC_VM_NAME} VM"
    return 1
  elif ! xe_vm_net_attach "${HTPC_VM_NAME}" "${HTPC_VM_NET}"; then
    logError "Failed to attach network to VM"
    return 1
  elif ! xe_vm_pci_attach "${HTPC_VM_NAME}" "${PCI_GPU}"; then
    logError "Failed to attach PCI device to VM"
    return 1
  elif ! htpc_usb_mount; then
    logError "Failed to setup USB passthrough"
    return 1
  elif ! xe_vm_start "${HTPC_VM_NAME}"; then
    logError "Failed to start ${HTPC_VM_NAME}"
    return 1
  elif ! install_htpc_pugins; then
    return 1
  else
    logInfo "HTPC Ready to install"
  fi

  return 0
}

htpc_usb_mount() {
  local htpc_usb_devices
  IFS="," read -r -a htpc_usb_devices <<<"${USB_DEVICES}"

  local var_usb_vid var_usb_pid var_usb_sn
  for device in "${htpc_usb_devices[@]}"; do
    var_usb_vid="UDEV_VID_${device}"
    var_usb_pid="UDEV_PID_${device}"
    var_usb_sn="UDEV_SN_${device}"

    if xe_vm_usb_attach "${HTPC_VM_NAME}" "${!var_usb_vid}" "${!var_usb_pid}" "${!var_usb_sn}"; then
      logInfo "Attached USB device ${device} to ${HTPC_VM_NAME}"
    else
      logError "Failed to attach USB device ${device} to ${HTPC_VM_NAME}"
      return 1
    fi
  done
}

install_htpc_pugins() {
  return 2
}

load_configuration() {
  # Determine BPKG's global prefix
  if [[ -z "${PREFIX}" ]]; then
    if [[ $(id -u || true) -eq 0 ]]; then
      PREFIX="/usr/local"
    else
      PREFIX="${HOME}/.local"
    fi
  fi

  # shellcheck disable=SC1091
  if ! source "${PREFIX}/lib/slf4.sh"; then
    echo "Failed to import slf4.sh"
    return 1
  elif ! source "${PREFIX}/lib/config.sh"; then
    logError "Failed to import config.sh"
    return 1
  fi

  # Load configuration
  local configs config
  IFS=":" read -r -a configs <<<".config/default.env:${LOCAL_CONFIG}"
  for config in "${configs[@]}"; do
    if ! config_load "${KOS_ROOT}/${config}"; then
      return 1
    fi
  done

  # Load sol & Kosmos configuration
  if [[ -z "${DIR_SOL}" ]]; then
    logError "DIR_SOL is not set"
    return 1
  elif [[ -z "${DIR_SETUP}" ]]; then
    logError "DIR_SETUP is not set"
    return 1
  elif [[ -z "${DIR_XAPI}" ]]; then
    logError "DIR_XAPI is not set"
    return 1
  elif [[ -z "${DIR_BIN}" ]]; then
    logError "DIR_BIN is not set"
    return 1
  elif [[ -z "${XEN_HOST}" ]]; then
    logError "XEN_HOST is not set"
    return 1
  elif [[ -z "${XEN_USER}" ]]; then
    logError "XEN_USER is not set"
    return 1
  elif [[ -z "${XEN_PWD}" ]]; then
    logError "XEN_PWD is not set"
    return 1
  elif [[ -z "${HTPC_VM_NAME}" ]]; then
    logError "HTPC_VM_NAME is not set"
    return 1
  elif [[ -z "${HTPC_VM_RAM}" ]]; then
    logError "HTPC_VM_RAM is not set"
    return 1
  elif [[ -z "${HTPC_VM_VCPUS}" ]]; then
    logError "HTPC_VM_VCPUS is not set"
    return 1
  elif [[ -z "${HTPC_VM_DISK}" ]]; then
    logError "HTPC_VM_DISK is not set"
    return 1
  elif [[ -z "${HTPC_VM_NET}" ]]; then
    logError "HTPC_VM_NET is not set"
    return 1
  elif ! config_load "${DIR_SOL}/data/local.env"; then
    logError "Failed to load local configuration"
    return 1
  elif ! config_load "${DIR_SOL}/data/hardware.env"; then
    logError "Failed to load hardware configuration"
    return 1
  elif [[ -z "${PCI_GPU}" ]]; then
    logError "PCI_GPU is not set"
    return 1
  elif [[ -z "${USB_DEVICES}" ]]; then
    logError "USB_DEVICES is not set"
    return 1
  fi

  # shellcheck disable=SC1091
  if ! source "${DIR_XAPI}/src/xe_vm.sh"; then
    logError "Failed to load xe_vm.sh"
    return 1
  elif ! source "${DIR_SETUP}/src/net.sh"; then
    logError "Failed to load net.sh"
    return 1
  fi

  # Download XE CLI utility
  if ! nu_file_download "${DIR_BIN}/xe" "scp://${XEN_HOST}:22/opt/xensource/bin/xe" \
    "${XEN_USER}" "${XEN_PWD}"; then
    logFatal "Failed to download xe"
    return 1
  fi

  # Configure it into PATH
  PATH="${DIR_BIN}:${PATH}"
  export PATH

  if ! xe_create_connection "${XEN_HOST}"; then
    logError "Failed to connect to demers-qnap's management interface"
    return 1
  else
    logInfo "Connected successfully to demers-qnap's management interface"
  fi
}

# Constants
LOCAL_CONFIG=".config/demers.env:.config/demers-sol.env:.config/local.env"

###########################
###### Startup logic ######
###########################

# Get directory of this script
# https://stackoverflow.com/a/246128
KOS_SOURCE=${BASH_SOURCE[0]}
while [[ -L "${KOS_SOURCE}" ]]; do # resolve $KOS_SOURCE until the file is no longer a symlink
  KOS_ROOT=$(cd -P "$(dirname "${KOS_SOURCE}")" >/dev/null 2>&1 && pwd)
  KOS_SOURCE=$(readlink "${KOS_SOURCE}")
  [[ ${KOS_SOURCE} != /* ]] && KOS_SOURCE=${KOS_ROOT}/${KOS_SOURCE} # if $KOS_SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
KOS_ROOT=$(cd -P "$(dirname "${KOS_SOURCE}")" >/dev/null 2>&1 && pwd)
KOS_ROOT=$(realpath "${KOS_ROOT}/../../../..")

if [[ -p /dev/stdin ]] && [[ -z ${BASH_SOURCE[0]} ]]; then
  # This script was piped
  logFatal "This script cannot be piped"
elif [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
  # This script was sourced
  logFatal "This script cannot be sourced"
else
  # This script was executed
  setup
  exit $?
fi
