#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# This script is used to set up the local client environment on Linux. It configures the following:
# 1. Docker Desktop
# 2. Checkout the git repository
#
# Usage:
# Run: $ ./setup-linux.sh
#
# Todo:
# - Generalize this script by making the repo to be checked out a parameter/argument
# - Turn this script into a module in it's own git repo
# - Add logger instead of using echo
# - Get the last version of Docker Desktop instead of using a hard-coded fixed value (variable DOCKER_VER)
# - Autorun needs to pass back the original arguments
#
# NOTE: Designed to work with Linux Mint

SETUP_VERSION="1.0.0"

main() {
  parse

  install_docker

  get_repo

  teardown_autorun

  read -rp "Execution successful! Press Enter to exit"
}

get_repo() {
  local repo_name
  repo_name=$(basename -- "${REPO_URL}")
  repo_name="${repo_name%.*}"

  # Directory where the git repo will be cloned
  repo="${HOME}/repos/${repo_name}" # All repositorys are cloned inside "~/repos"

  # Make sure directory exists
  mkdir -p "${repo}"

  pushd "${repo}" >/dev/null

  if ! git rev-parse --is-inside-work-tree >/dev/null; then
    echo "Cloning ${repo_name} into ${repo}"
    if ! git clone "${REPO_URL}" --branch "${REPO_BRANCH}" "${repo}"; then
      echo "Failed to clone ${repo_name}"
    fi
  else
    echo "Repo ${repo_name} already exists"
  fi

  if ! git rev-parse --is-inside-work-tree >/dev/null; then
    echo "We failed to retrieve git repository ${repo_name}"
    exit 1
  fi

  popd >/dev/null
}

configure_autostart() {

  local service_name="docker-desktop"
  local cmd="systemctl --user enable --now ${service_name}"
  local autostart_file="${HOME}/.config/autostart/${service_name}.desktop"

  local temp
  temp=$(
    cat <<END
[Desktop Entry]
Type=Application
Name=Docker Desktop
Exec=@EXECUTE@
END
  )
  # Replace content in template
  temp=${temp//@EXECUTE@/"${cmd}"}

  # Create autostart for current user
  mkdir -p "$(dirname "${autostart_file}")"
  echo "${temp}" | tee "${autostart_file}" >/dev/null
  chmod +x "${autostart_file}"
}

install_docker() {
  # Only install if it's not already installed
  local docker_installed
  is_installed docker_installed "docker-desktop"
  if [[ "${docker_installed}" = false ]]; then
    echo "docker-desktop is not installed"

    # Download Docker Desktop installer
    local docker_installer="${ROOT}/download/docker-desktop-${DOCKER_VER}-${DOCKER_ARCH}.deb"
    local url_installer="https://desktop.docker.com/linux/main/${DOCKER_ARCH}/docker-desktop-${DOCKER_VER}-${DOCKER_ARCH}.deb"

    if [[ -f "${docker_installer}" ]]; then
      : # File already downloaded
    else
      echo "Downloading $(basename "${docker_installer}")..."
      mkdir -p "$(dirname "${docker_installer}")"
      wget "${url_installer}" --show-progress -O "${docker_installer}"
    fi

    # Add Docker's official GPG key:
    echo "Configuring docker-desktop repo..."

    sudo apt-get update
    sudo apt-get install ca-certificates curl gnupg
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    # Add the repository to Apt sources:
    local codename
    codename=$(. /etc/os-release && echo "${UBUNTU_CODENAME}")
    echo \
      "deb [arch=${DOCKER_ARCH} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      ${codename} stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
    sudo apt-get update

    # Install docker desktop
    echo "Installing docker-desktop..."
    sudo apt-get -y install "${docker_installer}" || true

    # Add missing permissions
    echo "Configuring permissions for docker-desktop..."
    local user
    user=$(whoami)
    sudo usermod -aG kvm "${user}"

    # We want docker to start automatically
    configure_autostart

    # Reboot needed to get docker running
    host_reboot
  else
    echo "docker-desktop is already installed"
  fi

  # Wait until docker is found to be running
  until docker ps >/dev/null 2>&1; do
    echo "Waiting for docker to be running"
    sleep 1
  done

  echo "Docker is running"
}

host_reboot() {
  setup_autorun

  echo "A reboot is required. This script will be launched automatically at next logon."
  read -rp "Is it OK to reboot now? (y/n) " yn
  case ${yn} in
  [yY])
    sudo reboot
    exit 0
    ;;
  [nN])
    echo "No reboot requested. Please reboot manually when ready. This script will be launched automatically at next logon."
    exit 0
    ;;
  *)
    echo "Invalid answer: ${yn}"
    exit 1
    ;;
  esac
}

setup_autorun() {
  local temp
  temp=$(
    cat <<END
[Desktop Entry]
Type=Application
Name=@NAME@
Exec=@EXECUTE@
END
  )
  local cmd="gnome-terminal -- bash -c \"${ME}\""

  # Replace content in template
  temp=${temp//@EXECUTE@/"${cmd}"}
  temp=${temp//@NAME@/"$(basename "${ME}")"}

  mkdir -p "$(dirname "${AUTORUN_FILE}")"
  echo "${temp}" | tee "${AUTORUN_FILE}" >/dev/null
  chmod +x "${AUTORUN_FILE}"
}

teardown_autorun() {
  rm -f "${AUTORUN_FILE}"
}

is_installed() {
  declare -n _is_installed="$1"
  local pkg_name="$2"

  local status
  status="$(dpkg-query -W --showformat='${db:Status-Status}' "${pkg_name}" 2>&1)"
  if [[ "${status}" = installed ]]; then
    _is_installed=true
  else
    _is_installed=false
  fi
}

parse() {
  if [[ ${NUM_ARGS} -eq 0 ]]; then
    :
  else
    for i in "${ARGS[@]}"; do
      case ${i} in
      -h | --help)
        print_help
        exit 0
        ;;
      -v | --version)
        echo "${SETUP_VERSION}"
        exit 0
        ;;
      *)
        print_help
        echo "Unexpected arguments (${NUM_ARGS}): ${ARGS[*]}"
        exit 1
        ;;
      esac
    done
  fi
}

print_help() {
  local script
  script=$(basename "${ME}")

  echo "Setup your local linux environment as a client for work using Docker Desktop"
  echo ""
  echo "Usage: ${script} [-h|--help|]"
  echo "       ${script} [-v|--version]"
  echo ""
  echo "Options:"
  echo "  -h,--help       Print this usage message"
  echo "  -v,--version    Print the version of this tool"
  echo ""
}

###########################
###### Startup logic ######
###########################

# Stop on error
set -euo pipefail

# Keep a copy of entry arguments
NUM_ARGS="$#"
ARGS=("$@")

# Constants & Configuration
DOCKER_ARCH=$(dpkg --print-architecture)
# Update version from URL here: https://docs.docker.com/desktop/install/ubuntu/#install-docker-desktop
DOCKER_VER="4.26.1"

# Path Configuration
ME=$(realpath "$0")
if ROOT=$(git rev-parse --show-toplevel 2>/dev/null); then
  : # Success. ROOT contains root of git repo
else
  ROOT=$(dirname "${ME}")
fi

# Autorun this script in a terminal window
AUTORUN_FILE="${HOME}/.config/autostart/$(basename "${ME}").desktop"

REPO_URL="https://github.com/homeinfra/Horizon.git"
REPO_BRANCH="main"

# Call main function
main

# Exit gracefully
exit 0
