#!/usr/bin/env sh
# SPDX-License-Identifier: MIT
#
# This is the entry point for the dev container

pre-commit install

if [ "$#" -gt 0 ]; then
  exec "$@"
  exit $?
else
  echo "Welcome to Horizon's development container!"
  if [ -t 1 ]; then
    exec /bin/sh -i
  else
    sleep infinity
  fi
fi
